Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  config.vm.define "client" do |client|
    client.vm.hostname = "client"
    client.vm.network "private_network", ip: "192.168.56.15"
    client.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "1"
    end
  end

  config.vm.define "server" do |server|
    server.vm.hostname = "server"
    server.vm.network "private_network", ip: "192.168.56.20"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "1"
      disk_path = File.join(File.dirname(__FILE__), "backup_disk.vdi")
      unless File.exist?(disk_path)
        vb.customize ["createhd", "--filename", disk_path, "--size", "2048"]
        vb.customize ["storagectl", :id, "--name", "NVMe", "--add", "pcie", "--controller", "NVMe"]
        vb.customize ["storageattach", :id, "--storagectl", "NVMe", "--port", "0", "--device", "0", "--type", "hdd", "--medium", disk_path]
      end
      
    end
  end
end
