Vagrant.configure("2") do |config|
  config.vm.define "pxeserver" do |server|
    server.vm.box = "ubuntu/jammy64"
    server.vm.hostname = "pxeserver"
    server.vm.network "private_network", ip: "192.168.56.30", virtualbox__intnet: "pxenet"
    server.vm.network "forwarded_port", guest: 80, host: 8080
    server.vm.network "private_network", ip: "192.168.56.10", adapter: 3
    
    server.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    end

    server.vm.provision "ansible" do |ansible|
      ansible.playbook = "ansible/provision.yml"
      #ansible.inventory_path = "ansible/hosts"
      ansible.host_key_checking = false
      ansible.limit = "all"
    end
  end

  config.vm.define "pxeclient" do |client|
    client.vm.box = "ubuntu/jammy64"
    client.vm.hostname = "pxeclient"
    client.vm.network "private_network", ip: "192.168.56.31", virtualbox__intnet: "pxenet"
    
    client.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus = 2
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--nic1", "intnet", "--intnet1", "pxenet", "--boot1", "net", "--boot2", "none", "--boot3", "none", "--boot4", "none"]
      vb.customize ["modifyvm", :id, "--nic2", "nat"]
    end
  end
end
