Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "my-custom-box"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "my-custom-box-build"
    vb.memory = "1024"
    vb.cpus = 2
  end

  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "playbook.yml"
  end
end
