# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :nginx => {
    :box_name => "generic/ubuntu2204",
    :vm_name => "nginx",
    :extra_nic => {
      :ip => "192.168.56.25",
      :netmask => "255.255.255.0"
    }
  }
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.hostname = boxconfig[:vm_name] 

      if boxconfig[:extra_nic]
        box.vm.network "private_network",
          ip: boxconfig[:extra_nic][:ip],
          netmask: boxconfig[:extra_nic][:netmask]
      end

      box.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 2
      end

      box.vm.provision "shell", inline: <<-SHELL
        mkdir -p ~root/.ssh
        cp ~vagrant/.ssh/authorized_keys ~root/.ssh/
        sed -i 's/#PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config
        systemctl restart sshd
      SHELL
    end
  end
end
