client
dev tun
proto udp
remote 192.168.56.10 1207
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
ca ca.crt
cert client.crt
key client.key
route 10.10.10.0 255.255.255.0 
comp-lzo
verb 3
