Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"

  config.vm.provider "virtualbox" do |v|
    v.memory = 1512
    v.cpus = 2
  end

  boxes = [
    { :name => "web", :ip => "192.168.56.10" },
    { :name => "log", :ip => "192.168.56.15" }
  ]

  boxes.each do |opts|
    config.vm.define opts[:name] do |config|
      config.vm.hostname = opts[:name]
      config.vm.network "private_network", ip: opts[:ip]
      
      config.vm.provision "shell", inline: <<-SHELL
        timedatectl set-timezone UTC
        apt-get update && apt-get install -y ntpdate
        ntpdate pool.ntp.org
      SHELL
    end
  end
end
