[frontend]
192.168.56.10

[backend:children]
backend_master
backend_slave

[backend_master]
192.168.56.20

[backend_slave]
192.168.56.21

[monitoring]
192.168.56.30

[logging]
192.168.56.40

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_private_key_file=~/.vagrant.d/insecure_private_key
ansible_user=vagrant
domain_name=lab.diplom.com
public_base_url=https://lab.diplom.com
restic_server_user=restic

# =============================================================================
# frontend (front.yml)
# =============================================================================
[frontend:vars]
restic_label=frontend

# =============================================================================
# backend (back.yml)
# =============================================================================
[backend:vars]
db_wp_name=wordpress_db
db_wp_user=wp_user
repl_user=repl_user

[backend_master:vars]
db_role=master
restic_label=backend_master

[backend_slave:vars]
db_role=slave
restic_label=backend_slave

# =============================================================================
# monitoring (monitoring.yml)
# =============================================================================
[monitoring:vars]
alertmanager_smtp_server=smtp.mail.ru:587
alertmanager_smtp_user=profi-remstroy@mail.ru
alertmanager_email_to=silva-93@mail.ru
