---
- name: Настройка UFW для всех узлов
  hosts: all
  become: yes
  vars:
    base_ufw_rules:
      - { rule: allow, port: "22", proto: tcp, from: "192.168.56.0/24" }
      - { rule: allow, port: "22", proto: tcp, from: "10.0.2.2" }
      - { rule: allow, port: "9100", proto: tcp, from: "10.10.10.30" }
    frontend_ufw_rules:
      - { rule: allow, port: "80", proto: tcp, from: any }
      - { rule: allow, port: "443", proto: tcp, from: any }
    backend_master_ufw_rules:
      - { rule: allow, port: "3306", proto: tcp, from: "10.10.10.21" }
      - { rule: allow, port: "3306", proto: tcp, from: "10.10.10.40" }
      - { rule: allow, port: "80", proto: tcp, from: "10.10.10.10" }
    backend_slave_ufw_rules:
      - { rule: allow, port: "3306", proto: tcp, from: "10.10.10.20" }
      - { rule: allow, port: "3306", proto: tcp, from: "10.10.10.40" }
      - { rule: allow, port: "80", proto: tcp, from: "10.10.10.10" }
    monitoring_ufw_rules:
      - { rule: allow, port: "9100", proto: tcp, from: "10.10.10.0/24" }
      - { rule: allow, port: "9090", proto: tcp, from: "10.10.10.10" }
      - { rule: allow, port: "3000", proto: tcp, from: "10.10.10.10" }
      - { rule: allow, port: "9093", proto: tcp, from: "10.10.10.10" }
    logging_ufw_rules:
      - { rule: allow, port: "3100", proto: tcp, from: "10.10.10.0/24" }
      - { rule: allow, port: "9100", proto: tcp, from: "10.10.10.0/24" }
      - { rule: allow, port: "8000", proto: tcp, from: "10.10.10.0/24" }
      - { rule: allow, port: "6033", proto: tcp, from: "10.10.10.0/24" }
      - { rule: allow, port: "2049", proto: tcp, from: "10.10.10.0/24" }
    ufw_rules: >-
      {{
        base_ufw_rules
        + (frontend_ufw_rules if 'frontend' in group_names else [])
        + (backend_master_ufw_rules if 'backend_master' in group_names else [])
        + (backend_slave_ufw_rules if 'backend_slave' in group_names else [])
        + (monitoring_ufw_rules if 'monitoring' in group_names else [])
        + (logging_ufw_rules if 'logging' in group_names else [])
      }}

  tasks:
    - name: Применение правил UFW
      ufw:
        rule: "{{ item.rule }}"
        port: "{{ item.port }}"
        proto: "{{ item.proto | default('tcp') }}"
        from: "{{ item.from | default('any') }}"
      loop: "{{ ufw_rules }}"
      notify: Reload UFW

    - name: UFW запрет входящих по умолчанию
      ufw:
        direction: incoming
        default: deny
      notify: Reload UFW

    - name: UFW разрешение исходящих по умолчанию
      ufw:
        direction: outgoing
        default: allow
      notify: Reload UFW

    - name: UFW включение файервола
      ufw:
        state: enabled
        logging: "on"
      notify: Reload UFW

  handlers:
    - name: Reload UFW
      command: ufw reload
      changed_when: false
