interface={{ pxe_interface }}
bind-interfaces
dhcp-range={{ pxe_interface }},{{ dhcp_range_start }},{{ dhcp_range_end }}
dhcp-boot=pxelinux.0
enable-tftp
tftp-root={{ tftp_root }}/amd64
log-dhcp
log-queries
